name: SimplyVanish
main: dev.chickeneer.simplyvanish.SimplyVanish
version: 2.1.0
api-version: 1.16
description: This plugin is for hiding the online status of a joined user.
authors: [ chickeneer, asofold, jeikobu__ ]
website: https://github.com/chickeneer/SimplyVanish
softdepend:
  - LibsDisguises
  - dynmap
  - ProtocolLib